declare const __APP_ENV__: {
  SOULSIDE_API_BASE_URL: string;
  SOULSIDE_REGISTRATION_API_BASE_URL: string;
  SOULSIDE_DYTE_TRANSCRIPTS_INGESTION_API_BASE_URL: string;
  SOULSIDE_IN_SESSION_SOCKET_URL: string;
  SOULSIDE_SESSION_TRANSCRIPT_LLM_API_URL: string;
  SOULSIDE_APP_DOMAIN: string;
  SOULSIDE_SOULSIDE_DOMAIN: string;
  SOULSIDE_APP_ENV: string;
  SOULSIDE_APP_IDENTIFIER: string;
  SOULSIDE_PLATFORM_URL: string;
};
