export const API_BASE_URL = process.env.SOULSIDE_API_BASE_URL;
export const REGISTRATION_API_BASE_URL = process.env.SOULSIDE_REGISTRATION_API_BASE_URL;
export const DYTE_TRANSCRIPTS_INGESTION_API_BASE_URL =
  process.env.SOULSIDE_DYTE_TRANSCRIPTS_INGESTION_API_BASE_URL;
export const IN_SESSION_SOCKET_URL = process.env.SOULSIDE_IN_SESSION_SOCKET_URL;
export const SESSION_TRANSCRIPT_LLM_API_URL = process.env.SOULSIDE_SESSION_TRANSCRIPT_LLM_API_URL;
export const APP_DOMAIN = process.env.SOULSIDE_APP_DOMAIN;
export const SOULSIDE_DOMAIN = process.env.SOULSIDE_SOULSIDE_DOMAIN;
export const APP_ENV = process.env.SOULSIDE_APP_ENV;
export const APP_IDENTIFIER = process.env.SOULSIDE_APP_IDENTIFIER;
export const PLATFORM_URL = process.env.SOULSIDE_PLATFORM_URL;
