export const API_BASE_URL = __APP_ENV__.SOULSIDE_API_BASE_URL;
export const REGISTRATION_API_BASE_URL = __APP_ENV__.SOULSIDE_REGISTRATION_API_BASE_URL;
export const DYTE_TRANSCRIPTS_INGESTION_API_BASE_URL =
  __APP_ENV__.SOULSIDE_DYTE_TRANSCRIPTS_INGESTION_API_BASE_URL;
export const IN_SESSION_SOCKET_URL = __APP_ENV__.SOULSIDE_IN_SESSION_SOCKET_URL;
export const SESSION_TRANSCRIPT_LLM_API_URL = __APP_ENV__.SOULSIDE_SESSION_TRANSCRIPT_LLM_API_URL;
export const APP_DOMAIN = __APP_ENV__.SOULSIDE_APP_DOMAIN;
export const SOULSIDE_DOMAIN = __APP_ENV__.SOULSIDE_SOULSIDE_DOMAIN;
export const APP_ENV = __APP_ENV__.SOULSIDE_APP_ENV;
export const APP_IDENTIFIER = __APP_ENV__.SOULSIDE_APP_IDENTIFIER;
export const PLATFORM_URL = __APP_ENV__.SOULSIDE_PLATFORM_URL;
